services:
   sqladmin_my:
      image: phpmyadmin/phpmyadmin:latest
      ports:
         - "${MYADMIN_WEBPORT:-25561-25569}:80"
      volumes:
         - pgadmin-store:/var/lib/pgadmin
      restart: always
      environment:
         PMA_HOST: ${MYSQL_PMA_HOST:-localhost}
         PMA_PORT: ${MYSQL_PMA_PORT:-3306}
      networks:
         - frontend_bridge
         - database_network_default
      healthcheck:
         test: wget -O - http://localhost:80/misc/ping
         interval: 1s
         timeout: 1s
         retries: 3
         start_period: 10s
   sqladmin_pg:
      image: dpage/pgadmin4:latest
      ports:
         - "${PGADMIN_WEBPORT:-25561-25569}:80"
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-sqladmin@localhost.local}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-password}
      restart: always
      volumes:
         - pgadmin-store:/var/lib/pgadmin
      networks:
         - frontend_bridge
         - database_network_default
      healthcheck:
         test: wget -O - http://localhost:80/misc/ping
         interval: 1s
         timeout: 1s
         retries: 3
         start_period: 10s
volumes:
   db-pg-store:
   db-my-store:
   myadmin-store:
   pgadmin-store:
networks:
   frontend_bridge:
      external: true
   database_network_default:
   
